# Generated by Django 4.1.7 on 2023-03-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='HanJi',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('character', models.CharField(max_length=2, unique=True)),
                ('sip_ngoo_im', models.CharField(max_length=15)),
                ('hong_im', models.CharField(max_length=15)),
                ('POJ', models.CharField(max_length=15)),
                ('TL', models.CharField(max_length=15)),
                ('BP', models.CharField(max_length=15)),
            ],
        ),
    ]
